[features]
seeds = false
[programs.devnet]
soltransfer = "4vnihPiwkRbNNa5WJCzPbp27exRGz3Lm1dzfaLXEEHcJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rudransh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
